FROM python:3.12.3


WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY xml_to_csv_bulk.py .

# Directory to mount volume
RUN mkdir -p /app/downloads

CMD [ "python", "xml_to_csv_bulk.py" ]